export const join = (req, res) =>
  res.render("join", { pageTitle: "join it is" });
export const login = (req, res) =>
  res.render("login", { pageTitle: "login it is" });
export const seeUsers = (req, res) =>
  res.render("seeUsers", { pageTitle: "seeUsers it is" });
export const seeUser = (req, res) =>
  res.render("seeUser", { pageTitle: "seeUser it is" });
export const editProfile = (req, res) =>
  res.render("editProfile", { pageTitle: "editProfile it is" });
